#!/bin/bash

make clean
make comp-test
./comp-test input.txt > /dev/null #debug.txt
# grep -E "^Encode" debug.txt > encode.txt
# grep -E "^Decode" debug.txt > decode.txt
diff --brief input.txt decoded.txt
