#!/bin/bash

cleanup() {
    kill $proxy_pid
    kill $server_pid
    kill $client_pid
}

trap cleanup EXIT INT TERM

make clean default

python rdcc_proxy.py -t "$1" > /dev/null &
proxy_pid=$!

sleep 0.1

./server > ignore/server.log &
server_pid=$!

sleep 0.1

./client "$2" &
client_pid=$!

wait $server_pid
